""" Context:
Towards the end of the good path in Christeena's route, the couple is alone in the cabin, talking
to each other and being appreciative of the other, leading to Christeena kissing Alex and leading
to the implication that the two had sex, similar to Brittney's route. The next scene starts the
next day with Alex waiting alone at the bus stop drinking from a water bottle."""

label next_day:
    "Suddenly, I heard footsteps from behind me."
    "I turned around to see that it was Brittney approaching me."
    "Odd. I though she would've left by now to drive to school."
    "She had an unusually large smile on her face."
    "I gave a quick casual wave before turning back around."
    "A few seconds later, she was right next to me, where she proceeded to rest her arm on my shoulder and lean uncomfortably close towards the side of my head."
    "Without moving my head, I looked towards her. She still had that big grin plastered on."
    b "Hi."
    "She said it so casually, yet so creepily."
    a "Hi."
    "I then looked forward again."
    "She lightly poked my shoulder."
    b "So?"
    "I turned my eyes towards her again."
    a "So...?"
    "I took a sip from my bottle."
    "She leaned in even closer."
    b "Was her pussy as good as you thought it would be?"
    menu:
        "Choke on drink.":
            pass

    "The water spewed out of my mouth and nose in an instant as I started coughing like a madman!"
    "A few seconds passed before I jolted my head towards her."
    a "The fuck?!"
    "My face was noticeably wet from both the spat-out water and tears from the coughing, but I didn't care."
    b "I mean, it was your first time, too, right?"
    b "I know guys tend to wonder these kinds of things going in, so I was curious if it lived up to your expectations."
    "I just stared at her with both confusion and frustration."
    a "Okay, first of all, you can't just ask someone that!"
    b "I can't? Then how did I just do it?"
    a "..."
    a "Second of all, what I do in my free time is none of your business!"
    b "It is when {i}my sister{/i} is what you're doing in your free time!"
    "...{w}she's got me there."
    a "And third of all...!"
    "I looked around to see if anyone was nearby."
    "Nobody."
    "I lowered my voice a bit before finishing:"
    a "...how did you even find out about all of that?"
    "Her sly grin vanished in the blink of an eye."
    b "Seriously?"
    "She sounded genuinely confused."
    a "Uh... yeah."
    b "Dude. Did you seriously think that Christeena wasn't going to tell her closest female friend that she lost her v-card?"
    b "Shit like that's a big deal, especially for girls."
    b "I mean, what, have you not told Donald?"
    a "Well... no."
    "Her eyes widened as she gave a loud gasp."
    b "So he doesn't know?"
    a "Brittney, I swear to God if you tell Donald--!"
    d "Tell me what?"
    "I quickly turned around to find him approaching us."
    a "Uh, well..."
    b "Alex and Christeena fucked last night!"
    a "{b}{i}BRITTNEY!!!{/i}{/b}"
    b "What? You clearly don't have the balls to tell him!"
    b "And yet you had balls last night that were slapping against my sister's crotch!"
    "I let out an embarrassed groan as I covered my face with my hands."
    "Why, oh why, did you have to tell {i}Brittney{/i}, of all people, Christeena?"
    b "Anyway, I better get going before my parking spot is taken. See you at school!"
    d "Uh, yeah. See ya."
    "I could hear her walk away, but my face was still covered up."
    "A few seconds passed before the silence was broken."
    d "So, uh... was she... serious?"
    d "You and Christeena...?"
    "I took my hands off my face and turned towards him."
    "Sighing and giving a smirk, I replied:"
    a "Yeah."
    "He stared at me for another second or two before raising his hand towards me with a smile."
    d "Niiiiiice!"
    "I rolled my eyes before accepting his high-five offer."
    d "Don't worry, I won't ask for the details if you don't wanna tell them."
    a "Thanks; I appreciate it."
    d "I just have one question."
    a "...yes?"
    d "You used protection, right?"
    a "Heh. Yeah."
    a "Chris told me about the box of condoms you had 'hidden' in the cabin."
    d "Hahahahaha!"
    d "Man, I forgot all about those!"
    d "Well, I'm glad they ended up being used!"
    d "Of course, I always envisioned that they'd be used by {i}me{/i}, but I digress."
    a "Don't worry; there's still plenty left."
    d "Just enough to last you and Chris a weekend, right?"
    "We laughed for a few seconds."
    "Man, it actually was pretty nice to talk about this with Donald; I guess I understand what Brit was talking about."
    d "Well, I'm happy for you, man. It's a pretty big step for you guys' relationship."
    a "Yeah, that's an understatement."
    d "I just can't believe you actually managed to persuade Christeena, of all girls, to actually do it."
    a "Actually, you're not going to believe this: {i}she's{/i} the one who made the first move last night."
    d "..."
    d "You're right. I don't believe it."
    d "Christeena \"The Princess of Prude\" Truman made the first move?"
    a "Trust me, I was just as confused as you, but I wasn't exactly going to stop her."
    d "I don't blame you."
    d "I mean, if Brittney suddenly started making moves towards me, I'd be confused and asking questions, yet would have to be brain dead to have her stop."
    a "I dunno, man. I can see you telling her to stop."
    d "Do you?"
    a "Let's be real, dude. You'd be terrified of a kiss from her let alone sex."
    d "..."
    d "...well, I guess you never know some things until you try."
    a "Maybe."
    "We could then hear the bus approaching."
    d "Well, again, I'm happy for you guys."
    a "Thanks."
    "The bus then pulled up and we got on."
